In [5]:
#Import Statement
import numpy as np

In [8]:
# creating numpy array
np_arr = np.array([1,2,3,4,5])

#printing array
print(np_arr)

[1 2 3 4 5]


In [9]:
#creating numpy array like 1,2,3,4,5,6......
# np.arange(start=0,stop,step=1)
np_arr = np.arange(100)

print(np_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [16]:
#creating numpy array of even number from 1 to 99
np_even_arr = np.arange(1,100,2)

print(np_even_arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [38]:
#Creating numpy array from scratch
row,col = 3,3
#vector/matrix of zeros
zeros = np.zeros((row,col))
print(zeros)

#of ones
ones = np.ones((row,col))
print(ones)

#of constant value =  np.full((row,col,...),value)
full = np.full((row,col),7)
print(full)

#identity matrix 3*3
identity = np.identity(3,dtype=int)
print(identity)

#of random value
random = np.random.random((row,col)) # random values between 0 and 1
print(random)

#of randint value
randint = np.random.randint(0,10,size=(row,col))
print(randint)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0.7869833  0.22650609 0.33992711]
 [0.8468362  0.69605219 0.62033752]
 [0.28290386 0.86645763 0.29958018]]
[[4 6 5]
 [7 4 6]
 [2 9 6]]


In [28]:
#Vector -> 1D array
vector = np.array([1,2,3,4,5,6])
print("Vector:", vector)

#Matrix -> 2D array
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix: ", matrix)

#Tensor -> nD array where 3 <= n <= infinite
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor :", tensor)

Vector: [1 2 3 4 5 6]
Matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
#Array Properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

#dimention
print(arr.ndim)

#no. of element in each dimention
print(arr.shape)

#no. of element
print(arr.size)

#data type
print(arr.dtype)

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
#transpose of array
transpose = mat.T
print(transpose)

2
(3, 3)
9
int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:
# Array Reshaping
arr = np.arange(12)
print("Original Array:",arr)

#reshaping the array
reshaped = arr.reshape((3,4)) # convert the arr into 3*4 matrix
print("Reshped :",reshaped)

#undo reshaped array
flattend = arr.flatten() 
print("Flattened",flattend)

#ravel (return view(original), instead of copy) same as flatten
raveled = reshaped.ravel()
print("Ravel: ",raveled)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshped : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
